#!/bin/bash
#################################
#	Mysql Backup Script	#
#	nagios check		#
#				#
# Anton Antonov			#
# antonisimo@gmail.com		#
# ver 0.2			#
#################################

# changelog
# ver 0.2.1 - 18.09.2017

OPTS=$(getopt -o vhl: --long verbose,help,localcopy: -n 'parse-options' -- "$@")

if [ $? != 0 ]; then
	echo "Failed parsing options." >&2 ;
	exit 1 ;
fi

echo "$OPTS"
eval set -- "$OPTS"

localCopy=0
verbose=0
HELP=false

while true; do
	echo "qwe" $1
	case "$1" in
		-v | --verbose ) verbose=1; shift ;;
		-h | --help ) HELP=true; shift ;;
		-l | --localcopy ) localCopy=1; shift ;; 
		-- ) shift; break ;;
		* ) break ;;
	esac
done

echo VERBOSE=$verbose
echo HELP=$HELP

scriptLog="/var/log/mysqlBackup.log"
nagiosLog="/var/log/mysqlBackup.nagios"


########################################################

function logPrint() {

logMessage=$1

if [ -z $2 ]; then
        nagios=0
else
        if [[  $2 =~ ^[0-1]{1}$ ]]; then
                nagios=$2
        else
                nagios=0
        fi
fi

if [ -z $3 ]; then
        exitCommand=0
else
        if [[  $3 =~ ^[0-1]{1}$ ]]; then
                exitCommand=$3
        else
                exitCommand=0
        fi
fi

echo $(date) $logMessage >> $scriptLog

if [ $verbose -eq 1 ]; then
        echo $logMessage
fi

if [ $nagios -eq 1 ]; then
        echo $logMessage >> $nagiosLog
fi

if [ $exitCommand -eq 1 ]; then
        exit
fi

}

########################################################

logPrint $localCopy 0 0
if [ $localCopy -ne 1 ] && [ $localCopy -ne 0 ]; then
	logPrint "--local-copy accepts 0 or 1" 0 1
fi
